#!/usr/bin/env bash

files=$(find $1 -type f)
t=""
for file in $files; do
    for ip in $(head -10 $file); do
    lat=$(ping -c 1 -W 1 $ip | sed -nE 's/.*time=(.*) ms.*/\1/p')
    if [ -n "$lat" ]; then
        t=$t"\n"$lat
    fi
    done
done
t=$(echo -e "$t" | tail -n +2)

echo "$t" | awk '{ total += $1 } END { print total/NR }'
