#!/usr/bin/env bash

PING="ping -c 1 -W 1"
unamestr=`uname`
if [[ "$unamestr" == 'Darwin' ]]; then
   PING="ping -c 1 -t 1"
fi

files=$(find $1 -type f)
t=""
for file in $files; do
    for ip in $(head -30 $file); do
        if $PING $ip &> /dev/null; then
            echo "Keeping  $ip from $file"
        else
            echo "Deleting $ip from $file"
            sed -i "/$ip/d" $file
        fi
    done
done
