#!/usr/bin/env bash

PING="ping -c 1 -W 1"
unamestr=`uname`
if [[ "$unamestr" == 'Darwin' ]]; then
   PING="ping -c 1 -t 1"
fi

files=$(find $1 -type f)
t=""
for file in $files; do
    for ip in $(head -30 $file); do
        if $PING $ip | sed -nE 's/.*time=(.*) ms.*/\1/p'; then
            echo "Deleting $ip from $file"
            sed -i "/$ip/d" $file
        else
            echo "Keeping  $ip from $file"
        fi
    done
done

echo "$t" | awk '{ total += $1 } END { print total/NR }'
